# -*- coding: utf-8 -*-
"""Scrapy_Xpath_Updated1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1plgn4BykZmBwwCSWsI4fpjCunXprBlmO
"""
#step 1
pip install scrapy

#step 2
import requests
import pandas as pd
import csv
from scrapy.http import TextResponse

url = "https://talentedge.com/xlri-jamshedpur/financial-management-course" #Enter the Url
r = requests.get(url)
response = TextResponse(r.url,body=r.text,encoding="utf-8")
A=response.xpath("//title/text()").get()

B=response.xpath("normalize-space(/html/body/div[4]/section[1]/div/div/div/div[1]/div[1]/div/div/div[2]/div[1]/p)").get()

C=response.xpath("normalize-space(//*[@id='doverview']/div/div/div[1]/div[1]/div/div[1])").get()


D=response.xpath("normalize-space(//*[@id='doverview']/div/div/div[2]/ul)").get()

E=response.xpath("normalize-space(//*[@id='deligibility']/div/div/div/div/div[2]/div/div[1]/div/div/ul/li)").get()

F=response.xpath("normalize-space(//*[@id='dsyllabus']/div/div/div/div/div[1]/div/ul)").get()

n=response.xpath("normalize-space(//div[@class='program-details-total-pay-amt-right']/text())").get()
n=n.replace('+ GST','')

df = pd.DataFrame({'Course Link':url,'Title':A,'Short_description':B,'Description':xml_string,'Key Skills':D,'Prerequitsites':E,'Syllabus':F,'Price': n,},index=[1])

df.to_csv('result2.csv')

# from lxml import etree, html

# html_string = C

# tree = html.fromstring(html_string)

# xml_tree = etree.ElementTree(tree)

# xml_string = etree.tostring(xml_tree, pretty_print=True)

# #print(xml_string.decode())
